services:
  flask:
    build: ./flask
    ports:
      - "5001:5001"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/flask
    volumes:
      - ./flask:/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
volumes:
  postgres_data:
